version: "3.7"
networks:
  tracker-network:
    driver: bridge
  location-network:
    driver: bridge
services:
  trackit-redis:
    image: "redis:alpine"
    command: redis-server --appendonly yes
    volumes:
      - $PWD/redis-data:/var/lib/redis
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - tracker-network
    restart: on-failure
  trackit-rabbit:
      image: "rabbitmq:3-management"
      ports:
          - "5672:5672"
          - "8000:15672"
      networks:
        - tracker-network
        - location-network
      restart: on-failure
  tracker-service:
    build:
      context: ./tracker-service
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    networks:
      - tracker-network
    depends_on:
      - trackit-redis
      - trackit-rabbit
    restart: on-failure
    environment:
      - SPRING_REDIS_HOST=trackit-redis
      - SPRING_RABBITMQ_HOST=trackit-rabbit
  location-service:
    build:
      context: ./location-service
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    networks:
      - location-network
    depends_on:
      - trackit-rabbit
    restart: on-failure
    environment:
      - SPRING_RABBITMQ_HOST=trackit-rabbit
