version: "3.7"
networks:
  tracker-network:
    driver: bridge

services:
  redis-service:
    image: "redis:alpine"
    command: redis-server --appendonly yes
    volumes:
      - $PWD/redis-data:/var/lib/redis
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - tracker-network
    restart: on-failure

  tracker-service:
    build:
      context: ./tracker-service
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    networks:
      - tracker-network
    depends_on:
      - redis-service
    restart: on-failure
    environment:
      - SPRING_REDIS_HOST=redis-service
