spring:
  profiles:
    active: dev
  main:
    web-application-type: none
  application:
    name: tracker-service
  redis:
    client-name: tracker-service
  rabbitmq:
    port: 5672
  cloud:
    stream:
      bindings:
        input:
          accessListChannel:
            destination: accessList
            group: tracker-services
        output:
          locationChannel:
            destination: location
          accessListCallbackChannel:
            destination: accessListCallback
          requestAllAllowedChannel:
            destination: requestAllAllowed

#Common custom properties
redis:
  imei-set-name: ImeiAllowed
tcp:
  server:
    port: 9000

logging:
  level:
    pl.latusikl.trackit.trackerservice: DEBUG
---
spring:
  profiles: dev
  redis:
    host: localhost
    port: 6379
  rabbitmq:
    host: localhost
    username: guest
    password: guest

---

spring:
  profiles: deploy

  #Rabbit and Spring Cloud Streams
  rabbitmq:
    host: trackit-rabbit
    username: dath
    password: rxpFm6!st3C089
  redis:
    host: trackit-redis
---

spring:
  profiles: test

