spring:
  profiles:
    active: dev
  main:
    web-application-type: none
  application:
    name: tracker-service
  redis:
    client-name: tracker-service

#Common custom properties
redis:
  imei-set-name: ImeiAllowed
tcp:
  server:
    coban-port: 9000

---

spring:
  profiles: dev
  redis:
    host: localhost

logging:
  level:
    pl.latusikl.trackit.trackerservice: DEBUG

