spring:
  profiles:
    active: dev,non-dev
  main:
    web-application-type: none
  application:
    name: tracker-service
  redis:
    client-name: tracker-service
  cloud:
    stream:
      bindings:
        input:
          accessListChannel:
            destination: accessList
            group: tracker-services
        output:
          locationChannel:
            destination: location
          accessListCallbackChannel:
            destination: accessListCallback
          requestAllAllowedChannel:
            destination: requestAllAllowed

#Common custom properties
redis:
  imei-set-name: ImeiAllowed
tcp:
  server:
    coban-port: 9000

---

spring:
  profiles: dev
  redis:
    host: localhost
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

logging:
  level:
    pl.latusikl.trackit.trackerservice: DEBUG

---
spring:
  profiles: test

