spring:
  profiles:
    active: dev
  main:
    web-application-type: none
  application:
    name: tracker-service
  redis:
    client-name: tracker-service

#Common custom properties
redis:
  imei-set-name: ImeiAllowed
tcp:
  server:
    coban-port: 9000

---

spring:
  profiles: dev
  redis:
    host: localhost
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        locationChannel:
          destination: location
          group: tracker-services
        accessListChannel:
          destination: accessList
          group: tracker-services
        accessListCallbackChannel:
          destination: accessListCallback

logging:
  level:
    pl.latusikl.trackit.trackerservice: DEBUG

---
spring:
  profiles: test

