version: "3.8"
services:
    trackItPostgre:
        image: postgres:13
        restart: always
        environment:
            POSTGRES_PASSWORD: pass
            POSTGRES_USER: user
            POSTGRES_DB: TrackItDB
        ports:
            - 5432:5432
    # tracItPgAdmin:
    #     image: dpage/pgadmin4
    #     restart: always
    #     environment:
    #         PGADMIN_LISTEN_PORT: 80
    #         PGADMIN_DEFAULT_EMAIL: admin@admin.com
    #         PGADMIN_DEFAULT_PASSWORD: pass
    #     ports:
    #         - 7000:80
