server:
  port: 8090
spring:
  profiles:
    active: dev
    application:
      name: location-service

database:
  host: localhost
  name: TrackItDB
  pass: pass
  user: user

---
spring:
  profiles: dev

#Rabbit and Spring Cloud Streams
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        locationChannel:
          destination: location
          group: location-services
        accessListChannel:
          destination: accessList
          group: location-services
        accessListCallbackChannel:
          destination: accessListCallback

#Database
  jpa:
    hibernate:
      ddl-auto: none
      dialect: PostgreSQL9Dialect
  datasource:
    url: jdbc:postgresql://${database.host}:5432/${database.name}
    username: ${database.user}
    password: ${database.pass}
    initialization-mode: always

logging:
  level:
    pl.latusikl.trackit.locationservice: DEBUG

security:
  secret: p@@@XN8pFfG^Av473oM2@!HJRyQR#gWR7r^OAN&wAfn!*r54KDfzN#vzVYH5fbbg3Z81%^fp*h%FQ&feU43J$5S02NAAeUqU8CB
  allowed-hosts:
    - '*'
  expiration-time: 1800000
---
spring:
  profiles: test
