server:
  port: 8090
spring:
  profiles:
    active: dev
    application:
      name: location-service

---
spring:
  profiles: dev

#Rabbit and Spring Cloud Streams
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        locationChannel:
          destination: location
          group: location-services
        accessListChannel:
          destination: accessList
          group: location-services
        accessListCallbackChannel:
          destination: accessListCallback

#Database
  jpa:
    hibernate:
      ddl-auto: none
      dialect: PostgreSQL9Dialect
  datasource:
    url: jdbc:postgresql://localhost:5432/TrackItDB
    username: user
    password: pass
    initialization-mode: always

logging:
  level:
    pl.latusikl.trackit.locationservice: DEBUG

---
spring:
  profiles: test
