server:
  port: 8090
spring:
  profiles:
    active: dev
    application:
      name: location-service

  rabbitmq:
    port: 5672

  cloud:
    stream:
      bindings:
        input:
          locationChannel:
            destination: location
            group: location-services
          accessListCallbackChannel:
            destination: accessListCallback
            group: location-services
          requestAllAllowedChannel:
            destination: requestAllAllowed
            group: location-services
        output:
          accessListChannel:
            destination: accessList

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect
  datasource:
    initialization-mode: always


database:
  name: TrackItDB

logging:
  level:
    pl.latusikl.trackit.locationservice: DEBUG

security:
  secret: p@@@XN8pFfG^Av473oM2@!HJRyQR#gWR7r^OAN&wAfn!*r54KDfzN#vzVYH5fbbg3Z81%^fp*h%FQ&feU43J$5S02NAAeUqU8CB
  allowed-hosts:
    - '*'
  expiration-time: 1800000
---

spring:
  profiles: dev

#Rabbit and Spring Cloud Streams
  rabbitmq:
    host: localhost
    username: guest
    password: guest

#Database
  datasource:
    url: jdbc:postgresql://localhost:5432/${database.name}
    username: user
    password: pass

---
spring:
  profiles: deploy

  #Rabbit and Spring Cloud Streams
  rabbitmq:
    host: trackit-rabbit
    username: dath
    password: rxpFm6!st3C089

  #Database
  datasource:
    url: jdbc:postgresql://trackit-postgres:5432/${database.name}
    username: dath
    password: p2X3hP2Hfn61%h
---
spring:
  profiles: test
